### ISSUE TITLE
cd .... - Color of the dots

### ISSUE THREAD

**Issue by BarbzYHOOL** [oh-my-fish/plugin-cd#9]
Just wondering if it would be possible to make the extra dots in blue color when plugin-cd is installed. Actually they display in red as if CD wasn't installed

**Comment by SanCoder-Q** [comment]
@BarbzYHOOL I don't think there is a fix or even a workaround of this issue since the error color of the path is hardcoded in the c++ of the fish. As long as the parameter of the `plugin-cd` command, `builtin cd` command or even `command cd` command is not a potential file path, it will set it to the error color.

See https://github.com/fish-shell/fish-shell/blob/aba69ac6ae33ea087f5b116aaa8aa17ee37ea057/src/highlight.cpp#L821

But if you have any idea how could fix it, I will always be open to discussing. 😉

**Comment by BarbzYHOOL** [comment]
No idea, sorry.

**Comment by SanCoder-Q** [comment]
Close the issue since there is nothing we can do bout it. I hope one day, the fish developer would refactor the logic and provide a explicit way to anounce the argument of a function is a path or not.

**Comment by derekpovah** [comment]
I know this is old, but I just found this plugin and ran into this issue. Does anyone know if an issue has been raised upstream in the fish shell repo?
